baseURL = "https://example.com"
title = "DEMO WEBSITE"
description = "Actions Speak Louder Than Words!"
theme = "cactus"
copyright = "You" # deprecated, please use params.copyright
disqusShortname = "example" # Used when comments is enabled. Cactus will use site title if not set
# googleAnalytics = "UA-1234-5"


# summaryLength = 2

[outputFormats]
  [outputFormats.SearchIndex]
    path = "/search/"
    mediaType = "application/json"
    isPlainText = true
    notAlternative = true

[outputs]
  home = ["HTML", "RSS", "SearchIndex"]

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4

[params]

  [params.comments]
    enabled = false # default
    engine = "cactus_comments" # only disqus, utterances, and cactus_comments is supported
    [params.comments.utterances]
      repo = "<github_username>/<github_reponame>"
      label = "hugo-site-name" # you can use however you want to label your name in your repo's issues
      theme = "github-light"
    [params.comments.cactuscomments]
      siteName = "your_cactus_comments_sitename" # see https://cactus.chat/ on how to register your site name
      #serverUrl = "" # Defaults to https://matrix.cactus.chat:8448 (Cactus Chat public server)
      #serverName = "" # Defaults to cactus.chat

  # Customize the copyright years
  # Note: if startYear/endYear not provided, will use current year.
  [params.copyright]
    enabled = true # default
    name = "Robbi Nespu" # cactus will use title if copyright is not set
    startYear = 2020
    endYear = 2021

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/gohugoio"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/company/github/"
  [[params.social]]
    name = "email"
    link = "example@example.com"  # no need for "mailto:" in the head

[privacy]
  #[privacy.disqus]
  #  disable = false
  #[privacy.googleAnalytics]
  #  anonymizeIP = false
  #  disable = false
  #  respectDoNotTrack = false
  #  useSessionStorage = false
  #[privacy.instagram]
  #  disable = false
  #  simple = false
  [privacy.twitter]
    disable =  false #default: false
    enableDNT = true #default: false
    simple = false
  #[privacy.vimeo]
  #  disable = false
  #  enableDNT = false
  #  simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false

[caches]
[caches.getjson]
  dir = ":resourceDir/json"
  maxAge = -1

[related]
  includeNewer = true
  threshold = 10
  toLower = true
  [[related.indices]]
    name = "keywords"
    weight = 80
  [[related.indices]]
    name = "title"
    weight = 80
  [[related.indices]]
    name = "tags"
    weight = 100
  [[related.indices]]
    name = "date"
    weight = 60
  pattern = "2006"

languageCode = "en"
defaultContentLanguage = "en"
