colortheme = "dark" # dark, light, white, or classic
rss = true # generate rss feed. default value is false
googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
showAllPostsArchive = true # default:false
noindexArchive = false # default, set to true if you don't want search engines to index archive pages (should improve SEO)

# Home page settings
mainSections = "posts" # your main section
showAllPostsOnHomePage = true # default
postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
tagsOverview = false # show tags overview by default.
showProjectsList = false # show projects list by default (if projects data file exists).
projectsUrl = "https://github.com/gohugoio" # title link for projects list

# https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
dateFormat = "2006-01-02" # default

# Post page settings
show_updated = true # default
showReadTime = true # default
tocInline = false

# Search setting 
searchableSections = "posts, projects, client, photos" # you can check with .Section: {{ .Section }} to identify the section

# news timeline
[news]
    enabled = true # default: true
    enabledOnHomePage = false # default: false
    newsOnHomePage = 5

[comments]
enabled = false # default
engine = "cactus_comments" # only disqus, utterances, and cactus_comments is supported
[comments.utterances]
      repo = "<github_username>/<github_reponame>"
      label = "hugo-site-name" # you can use however you want to label your name in your repo's issues
      theme = "github-light"
[comments.cactuscomments]
      siteName = "RobbiNespu" # see https://cactus.chat/ on how to register your site name
      #serverUrl = "" # Defaults to https://matrix.cactus.chat:8448 (Cactus Chat public server)
      #serverName = "" # Defaults to cactus.chat

# the value of name should be an valid font awesome icon name (brands type)
# https://fontawesome.com/icons?d=gallery&s=brands
[[social]]
name = "github"
link = "https://github.com/gohugoio"
[[social]]
name = "linkedin"
link = "https://www.linkedin.com/company/github/"
[[social]]
name = "email"
link = "example@example.com"  # no need for "mailto:" in the head

# Customize the copyright years
# Note: if startYear/endYear not provided, will use current year.
[copyright]
enabled = true # default
name = "Robbi Nespu" # cactus will use title if copyright is not set
startYear = 2020
endYear = 2022
