baseURL = "https://example.com"
languageCode = "en-us"
title = "DEMO WEBSITE"
description = "Actions Speak Louder Than Words!"
theme = "cactus"
copyright = "You" # deprecated, please use params.copyright
disqusShortname = "example" # Used when comments is enabled. Cactus will use site title if not set
# googleAnalytics = "UA-1234-5"


# summaryLength = 2

# Main menu which appears below site header.
[menu]
  [[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
    identifier = "category"
    name = "Archives"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    identifier = "category1"
    name = "📝 Articles"
    url = "/categories/article"
    parent = "category"
    weight = 1
  [[menu.main]]
    identifier = "category2"
    name = "⭐️ Bookmarks"
    url = "/categories/bookmarks"
    parent = "category"
    weight = 2
  [[menu.main]]
    identifier = "category3"
    name = " 📅 RSVPs"
    url = "/categories/rsvp"
    parent = "category"
    weight = 3
  [[menu.main]]
    identifier = "category4"
    name = "💼 Statuses"
    url = "/categories/status"
    parent = "category"
    weight = 3
  [[menu.main]]
    identifier = "category5"
    name = "🚩 Check-in"
    url = "/categories/checkin"
    parent = "category"
    weight = 4
  [[menu.main]]
    identifier = "category6"
    name = "💬 Replies"
    url = "/categories/reply"
    parent = "category"
    weight = 5
  [[menu.main]]
    identifier = "category7"
    name = "🏆 Sports"
    url = "/categories/sport"
    parent = "category"
    weight = 6
  [[menu.main]]
    identifier = "category8"
    name = "👍 Favourites"
    url = "/categories/favourite"
    parent = "category"
    weight = 7
  [[menu.main]]
    identifier = "category9"
    name = "🔄 Reposts"
    url = "/categories/repost"
    parent = "category"
    weight = 8
  [[menu.main]]
    identifier = "category10"
    name = "📷 Photos"
    url = "/categories/photo"
    parent = "category"
    weight = 9

  [[menu.main]]
  identifier = "Projects"
  name = "Projects"
  url = "/projects"
  weight = 3

  [[menu.main]]
  identifier = "News"
  name = "News"
  url = "/news"
  weight = 4

  [[menu.main]]
  identifier = "About"
  name = "About"
  url = "/about"
  weight = 5

  [[menu.main]]
  name = "Search"
  url = "/search"
  weight = 6

[outputFormats]
  [outputFormats.SearchIndex]
    path = "/search/"
    mediaType = "application/json"
    isPlainText = true
    notAlternative = true

[outputs]
  home = ["HTML", "RSS", "SearchIndex"]

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4

[params]

  colortheme = "dark" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
  showAllPostsArchive = true # default:false
  noindexArchive = false # default, set to true if you don't want search engines to index archive pages (should improve SEO)

  # Home page settings
  description = "Hugo is a general-purpose website framework. Technically speaking, Hugo is a static site generator. Unlike systems that dynamically build a page with each visitor request, Hugo builds pages when you create or update your content."
  mainSections = "posts" # your main section
  mainSectionTitle = "Writings (article)"
  showAllPostsOnHomePage = true # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = false # show tags overview by default.
  showProjectsList = false # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/gohugoio" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = true # default
  showReadTime = true # default
  tocInline = false

  [params.comments]
    enabled = false # default
    engine = "cactus_comments" # only disqus, utterances, and cactus_comments is supported
    [params.comments.utterances]
      repo = "<github_username>/<github_reponame>"
      label = "hugo-site-name" # you can use however you want to label your name in your repo's issues
      theme = "github-light"
    [params.comments.cactuscomments]
      siteName = "your_cactus_comments_sitename" # see https://cactus.chat/ on how to register your site name
      #serverUrl = "" # Defaults to https://matrix.cactus.chat:8448 (Cactus Chat public server)
      #serverName = "" # Defaults to cactus.chat

  # Customize the copyright years
  # Note: if startYear/endYear not provided, will use current year.
  [params.copyright]
    enabled = true # default
    name = "Robbi Nespu" # cactus will use title if copyright is not set
    startYear = 2020
    endYear = 2021

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/gohugoio"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/company/github/"
  [[params.social]]
    name = "email"
    link = "example@example.com"  # no need for "mailto:" in the head

  # news timeline
  [params.news]
    enabled = true # default: true
    enabledOnHomePage = false # default: false
    newsOnHomePage = 5

[privacy]
  #[privacy.disqus]
  #  disable = false
  #[privacy.googleAnalytics]
  #  anonymizeIP = false
  #  disable = false
  #  respectDoNotTrack = false
  #  useSessionStorage = false
  #[privacy.instagram]
  #  disable = false
  #  simple = false
  [privacy.twitter]
    disable =  false #default: false
    enableDNT = true #default: false
    simple = false
  #[privacy.vimeo]
  #  disable = false
  #  enableDNT = false
  #  simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false

[caches]
[caches.getjson]
  dir = ":resourceDir/json"
  maxAge = -1

[related]
  includeNewer = true
  threshold = 10
  toLower = true
  [[related.indices]]
    name = "keywords"
    weight = 80
  [[related.indices]]
    name = "title"
    weight = 80
  [[related.indices]]
    name = "tags"
    weight = 100
  [[related.indices]]
    name = "date"
    weight = 60
	pattern = "2006"